version: "3.7"

services:
  redis:
    image: redis
    networks:
      - webnet

  bd:
    image: postgres
    networks:
      - webnet
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: auth

  backend:
    build: .
    volumes:
      - .:/usr/src/app
      - /user/src/app/node_modules
    ports:
      - 4000:4000
      - 9229:9229
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    command: ["yarn", "server"]

networks:
  webnet:

volumes:
  postgres:
