version: 2
aliases:
  - &docker_environment
    - image: circleci/node:chakracore-10.13.0
  - &checkout
    path: ~/repo
  - &restore_cache_dependencies
    name: "Restoring node_modules from the cache"
    keys:
      - node-modules-cache-{{ checksum "yarn.lock" }}
  - &run_yarn_install
    name: Installing Dependencies
    command: yarn install
  - &save_cache_dependencies
    name: "Saving node_modules into the cache"
    key: node-modules-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
  - &run_build
    name: Building an Image
    command: yarn build
  - &common_steps
    - checkout: *checkout
    - restore_cache: *restore_cache_dependencies
    - run: *run_yarn_install
    - save_cache: *save_cache_dependencies
    - setup_remote_docker
    - run: *run_build
  - &common_environment
    docker: *docker_environment
    steps: *common_steps
jobs:
  backend:
    <<: *common_environment
    working_directory: ~/repo/backend
  frontend:
    <<: *common_environment
    working_directory: ~/repo/frontend
workflows:
  version: 2
  build:
    jobs:
      # - api
      - frontend
